version = 0.1

[default.deploy.parameters]
stack_name = "xolabs-dev"
resolve_s3 = true
s3_prefix = "xolabs-dev"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
